export interface AuthorBook {
  id: string;
  image: string;
  title: string;
  price: string;
  oldPrice?: string;
  slug?: string;
  badge?: string;
  author?: string;
}

export interface RelatedBook {
  id: string;
  image: string;
  title: string;
  author: string;
  price: string;
  slug?: string;
  oldPrice?: string;
  originalPrice?: string;
  badge?: string;
  badgeType?: "sale" | "hot";
}

export interface BookDetailData {
  id?: string;
  slug?: string;
  title: string;
  author?: string;
  category?: string;
  price: string;
  numericPrice?: number;
  oldPrice?: string;
  originalPrice?: string;
  badge?: "SALE" | "HOT" | "NEW" | "SALE_AND_HOT" | "SALE_AND_NEW";
  availability?: "in-stock" | "on-sale" | "hot";
  image?: string;
  coverId?: string;
  summary?: string;
  description?: string;
  authorName?: string;
  authorImage?: string;
  authorQuote?: string;
  authorBooks?: AuthorBook[];
  relatedBooks?: RelatedBook[];
}

export function slugify(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, "")
    .replace(/[\s_-]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export const ALL_BOOKS_DATABASE: BookDetailData[] = [
  {
    id: "shop-1",
    slug: "a-poem-for-every-night",
    title: "A Poem for Every Night",
    author: "By CHAI IAM, HOF NURGIN",
    authorName: "Hof Nurgin & Chai Iam",
    authorImage: "/images/author-01.jpg",
    authorQuote: "“Poetry is the rhythmical creation of beauty in words, an intimate whisper to the quiet soul.”",
    price: "£22.00",
    numericPrice: 22.0,
    category: "Poetry",
    availability: "in-stock",
    image: "/images/Newest2.webp",
    coverId: "arrival-3",
    summary:
      "A magical collection of poems curated to inspire dreams, contemplation, and peaceful night thoughts across every season of life.",
    description:
      "A Poem for Every Night is an extraordinary bedside anthology gathering lyrical poetry and calming verses from timeless masters and modern voices alike. Beautifully bound with gilded foil detailing, this volume is crafted to become a treasured bedtime companion for readers seeking solace, wonder, and inspiration before sleep.",
    authorBooks: [
      {
        id: "ab-1",
        title: "The Quiet Room",
        price: "£15.00",
        image: "/images/shop9.jpg",
        slug: "the-quiet-room",
      },
      {
        id: "ab-2",
        title: "A Sense of Wonder",
        price: "£21.00",
        image: "/images/book_section8.webp",
        slug: "a-sense-of-wonder",
      },
    ],
    relatedBooks: [
      {
        id: "rb-1",
        title: "A Teaspoon of Earth and Sea",
        author: "By Dina Nayeri",
        price: "£20.00",
        image: "/images/shop1.jpg",
        slug: "a-teaspoon-of-earth-and-sea",
      },
      {
        id: "rb-2",
        title: "The Summer of Impossible Things",
        author: "By Ethan Morris",
        price: "£24.00",
        image: "/images/shop7.webp",
        slug: "the-summer-of-impossible-things",
        badge: "HOT",
        badgeType: "hot",
      },
      {
        id: "rb-3",
        title: "TRIO - Sarah Tolmie",
        author: "By Sarah Tolmie",
        price: "£21.00",
        image: "/images/shop9.jpg",
        slug: "trio-sarah-tolmie",
      },
      {
        id: "rb-4",
        title: "Henry & The Good Dog",
        author: "By Mesho Buvahr",
        price: "£17.00",
        image: "/images/Newest1.webp",
        slug: "henry-and-the-good-dog",
        badge: "SALE",
        badgeType: "sale",
      },
    ],
  },
  {
    id: "shop-2",
    slug: "a-teaspoon-of-earth-and-sea",
    title: "A Teaspoon of Earth and Sea",
    author: "By Dina Nayeri",
    authorName: "Dina Nayeri",
    authorImage: "/images/author-02.jpg",
    authorQuote: "“My books are marked down because most of them are marked with a deep longing for home on the edge by publishers.”",
    price: "£20.00",
    numericPrice: 20.0,
    category: "Fiction",
    availability: "in-stock",
    image: "/images/shop1.jpg",
    coverId: "shop1",
    summary:
      "Growing up in a coastal village by the Caspian Sea, Saba Hafezi weaves wondrous tales of America and family secrets in a deeply resonant novel.",
    description:
      "Set in a small Iranian village by the Caspian Sea in the early 1980s, Saba Hafezi dreams of America and weaves an intricate double life for her missing twin sister. A rich, lyrical tapestry exploring memory, displacement, and the boundless power of storytelling to heal fractured hearts.",
    authorBooks: [
      {
        id: "tb-1",
        image: "/images/Newest1.webp",
        title: "Henry & The Good Dog",
        price: "£22.00",
        slug: "henry-and-the-good-dog",
      },
      {
        id: "tb-2",
        image: "/images/shop3.jpg",
        title: "The Summer of Impossible Things",
        price: "£16.00",
        slug: "the-summer-of-impossible-things",
      },
      {
        id: "tb-3",
        image: "/images/shop6.jpg",
        title: "The Dark",
        price: "£18.00",
        slug: "the-dark",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/shop6.jpg",
        title: "The D.A.R.K",
        author: "By SAVANNA WALKER",
        price: "£18.00",
        slug: "the-dark",
      },
      {
        id: "rel-2",
        image: "/images/Newest1.webp",
        title: "Henry & The Good Dog",
        author: "By MESHO BUVAHR",
        price: "£22.00",
        oldPrice: "£25.00",
        badge: "SALE",
        badgeType: "sale",
        slug: "henry-and-the-good-dog",
      },
      {
        id: "rel-3",
        image: "/images/Newest2.webp",
        title: "A Poem for Every Night",
        author: "By CHAI IAM",
        price: "£22.00",
        slug: "a-poem-for-every-night",
      },
      {
        id: "rel-4",
        image: "/images/Newest4.webp",
        title: "Life of Pi",
        author: "By YANN MARTEL",
        price: "£18.00",
        badge: "HOT",
        badgeType: "hot",
        slug: "life-of-pi",
      },
    ],
  },
  {
    id: "shop-3",
    slug: "all-this-has-nothing-to-do-with-me",
    title: "All this has nothing to do with Me",
    author: "By BHUZUN NAHLAM, HOF NURGIN",
    authorName: "Bhuzun Nahlam",
    authorImage: "/images/author-03.jpg",
    authorQuote: "My books are marked down because most of them are marked with a on the edge by publishers.",
    price: "£20.00",
    numericPrice: 20.0,
    badge: "HOT",
    category: "Fiction",
    availability: "hot",
    image: "/images/shop2.jpg",
    coverId: "shop2",
    summary:
      "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur erit qui in ea voluptate",
    description:
      "All This Has Nothing to Do with Me dissects the intricacies of contemporary human connection with razor-sharp wit and poignant vulnerability. Following a protagonist navigating love, career illusions, and existential clarity, this novel is both humorous and deeply moving.",
    authorBooks: [
      {
        id: "at-1",
        image: "/images/Newest3.webp",
        title: "The Journey of Dreams",
        price: "£12.00",
        slug: "the-journey-of-dreams",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/book_section3.webp",
        title: "The Night Ocean",
        author: "By SERO GLAN, SI MODARSK",
        price: "£22.00",
        oldPrice: "£25.00",
        slug: "the-night-ocean",
        badge: "HOT",
        badgeType: "hot",
      },
      {
        id: "rel-2",
        image: "/images/Newest2.webp",
        title: "A Poem for Every night",
        author: "By CHAI IAM, HOF NURGIN",
        price: "£22.00",
        slug: "a-poem-for-every-night",
      },
      {
        id: "rel-3",
        image: "/images/Newest1.webp",
        title: "Henry & The Good Dog",
        author: "By MESHO BUVAHR, SAVANNA WALKER",
        price: "£22.00",
        oldPrice: "£25.00",
        slug: "henry-and-the-good-dog",
      },
      {
        id: "rel-4",
        image: "/images/shop8.jpg",
        title: "Ghost’s Afraid of the Dark",
        author: "By HOF NURGIN, MESHO BUVAHR",
        price: "£12.00",
        oldPrice: "£15.00",
        slug: "ghosts-around-of-the-dark",
      },
    ],
  },
  {
    id: "shop-4",
    slug: "bulle-and-pelle",
    title: "Bulle & Pelle",
    author: "By SAVANNA WALKER",
    authorName: "Savanna Walker",
    authorImage: "/images/author-02.jpg",
    authorQuote: "My books are marked down because most of them are marked with a on the edge by publishers.",
    price: "£16.00",
    originalPrice: "£19.00",
    numericPrice: 16.0,
    badge: "SALE_AND_HOT",
    category: "Children's",
    availability: "on-sale",
    image: "/images/book_section7.webp",
    coverId: "bestseller-7",
    summary:
      "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur erit qui in ea voluptate.",
    description:
      "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    authorBooks: [
      {
        id: "bp-1",
        image: "/images/shop6.jpg",
        title: "The DARK",
        price: "£18.00",
        slug: "the-dark",
      },
      {
        id: "bp-2",
        image: "/images/shop1.jpg",
        title: "A Teaspoon of Earth and Sea",
        price: "£18.00",
        slug: "a-teaspoon-of-earth-and-sea",
      },
      {
        id: "bp-3",
        image: "/images/shop9.jpg",
        title: "TRIO – Sarah Tolmie",
        price: "£21.00",
        oldPrice: "£24.00",
        badge: "SALE_AND_HOT",
        slug: "trio-sarah-tolmie",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/book_section3.webp",
        title: "The Night Ocean",
        author: "By SERO GLAN, SI MODARSK",
        price: "£22.00",
        slug: "the-night-ocean",
        badge: "SALE",
        badgeType: "sale",
      },
      {
        id: "rel-2",
        image: "/images/book_section5.webp",
        title: "Enemy - Jake Gyllenhaal",
        author: "By SERO GLAN",
        price: "£18.00",
        slug: "enemy-jake-gyllenhaal",
      },
      {
        id: "rel-3",
        image: "/images/book_section1.png",
        title: "The Journey of Visions toVictory",
        author: "By SANTOSH KUMAR MISHRA",
        price: "£35.00",
        slug: "the-journey-of-visions-to-victory",
      },
      {
        id: "rel-4",
        image: "/images/book_section4.webp",
        title: "The Assault",
        author: "By MESHO BUVAHR, SI MODARSK",
        price: "£19.00",
        slug: "the-assault",
      },
      {
        id: "rel-5",
        image: "/images/book_section6.webp",
        title: "When the Doves Disappeared",
        author: "By Hof Nurgin",
        price: "£19.00",
        slug: "when-the-doves-disappeared",
      },
      {
        id: "rel-6",
        image: "/images/book_section2.png",
        title: "Peter and the Wolf",
        author: "By John Walker",
        price: "£22.00",
        slug: "the-summer-of-impossible-things",
      },
    ],
  },
  {
    id: "shop-5",
    slug: "bulle-und-pelle",
    title: "Bulle und Pelle",
    author: "By Sero Glan, Shia Ung",
    authorName: "Sero Glan",
    authorImage: "/images/author-04 (1).jpg",
    authorQuote: "“My books are marked down because most of them are marked with a on the edge by publishers.”",
    price: "£28.00",
    numericPrice: 28.0,
    badge: "SALE",
    category: "Romance",
    availability: "on-sale",
    image: "/images/Newest5.webp",
    coverId: "arrival-6",
    summary:
      "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur erit qui in ea voluptate",
    description:
      "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    authorBooks: [
      {
        id: "ou-1",
        image: "/images/book_section3.webp",
        title: "The Night Ocean",
        price: "£22.00",
        oldPrice: "£25.00",
        badge: "SALE",
        slug: "the-night-ocean",
      },
      {
        id: "ou-2",
        image: "/images/book_section5.webp",
        title: "Enemy – Jake Gyllenhaal",
        price: "£18.00",
        slug: "enemy-jake-gyllenhaal",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/shop1.jpg",
        title: "A Teaspoon of Earth and Sea",
        author: "By SAVANNA WALKER, SHIA UNG",
        price: "£18.00",
        slug: "a-teaspoon-of-earth-and-sea",
      },
      {
        id: "rel-2",
        image: "/images/shop3.jpg",
        title: "Creative Life",
        author: "By HANA KIM, SAVANNA WALKER",
        price: "£16.00",
        badge: "HOT",
        badgeType: "hot",
        slug: "creative-life",
      },
    ],
  },
  {
    id: "shop-6",
    slug: "creative-life",
    title: "Creative Life",
    author: "By Hana Kim, Savanna Walker",
    authorName: "Hana Kim",
    authorImage: "/images/author-05.jpg",
    authorQuote: "“My books are marked down because most of them are marked with a on the edge by publishers.”",
    price: "£18.00",
    numericPrice: 18.0,
    badge: "HOT",
    category: "Romance",
    availability: "hot",
    image: "/images/shop3.jpg",
    coverId: "shop3",
    summary:
      "Practical insights and soulful practices for sustaining creativity, emotional resilience, and purpose in demanding times.",
    description:
      "Creative Life provides actionable guidance, habits, and mindset shifts for artists, entrepreneurs, and thinkers navigating burnout, creative blocks, and modern noise. A deeply empowering roadmap for lifelong craftsmanship.",
    authorBooks: [
      {
        id: "cl-1",
        image: "/images/Newest4.webp",
        title: "Life of Pi",
        price: "£12.00",
        slug: "life-of-pi",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/Newest5.webp",
        title: "Bulle und Pelle",
        author: "By SERO GLAN, SHIA UNG",
        price: "£28.00",
        badge: "SALE",
        badgeType: "sale",
        slug: "bulle-und-pelle",
      },
      {
        id: "rel-2",
        image: "/images/shop1.jpg",
        title: "A Teaspoon of Earth and Sea",
        author: "By SAVANNA WALKER, SHIA UNG",
        price: "£18.00",
        slug: "a-teaspoon-of-earth-and-sea",
      },
    ],
  },
  {
    id: "shop-7",
    slug: "dear-brain",
    title: "Dear Brain",
    author: "By MESHO BUVAHR",
    authorName: "Mesho Buvahr",
    authorImage: "/images/author-06 (1).jpg",
    authorQuote: "“My books are marked down because most of them are marked with a on the edge by publishers.”",
    price: "£18.00",
    numericPrice: 18.0,
    category: "For Kid",
    availability: "in-stock",
    image: "/images/shop4.jpg",
    coverId: "shop4",
    summary:
      "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur erit qui in ea voluptate",
    description:
      "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    authorBooks: [
      {
        id: "db-1",
        image: "/images/Newest1.webp",
        title: "Henry & The Good Dog",
        price: "£22.00",
        oldPrice: "£25.00",
        badge: "SALE",
        slug: "henry-and-the-good-dog",
      },
      {
        id: "db-2",
        image: "/images/shop5.jpg",
        title: "The Carrot Hunt",
        price: "£19.00",
        slug: "the-carrot-plan",
      },
      {
        id: "db-3",
        image: "/images/book_section4.webp",
        title: "The Assault",
        price: "£19.00",
        slug: "the-assault",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/Newest1.webp",
        title: "Henry & The Good Dog",
        author: "By MESHO BUVAHR, SAVANNA WALKER",
        price: "£22.00",
        oldPrice: "£25.00",
        badge: "SALE",
        badgeType: "sale",
        slug: "henry-and-the-good-dog",
      },
      {
        id: "rel-2",
        image: "/images/book_section3.webp",
        title: "The Night Ocean",
        author: "By SERO GLAN, SI MODARSK",
        price: "£22.00",
        oldPrice: "£25.00",
        badge: "SALE",
        badgeType: "sale",
        slug: "the-night-ocean",
      },
      {
        id: "rel-3",
        image: "/images/shop8.jpg",
        title: "Ghost’s Afraid of the Dark",
        author: "By HOF NURGIN, MESHO BUVAHR",
        price: "£12.00",
        oldPrice: "£15.00",
        badge: "SALE",
        badgeType: "sale",
        slug: "ghosts-around-of-the-dark",
      },
      {
        id: "rel-4",
        image: "/images/Newest4.webp",
        title: "Life of Pi",
        author: "By HANA KIM, HOF NURGIN",
        price: "£12.00",
        slug: "life-of-pi",
      },
    ],
  },
  {
    id: "shop-8",
    slug: "enemy-jake-gyllenhaal",
    title: "Enemy — Jake Gyllenhaal",
    author: "By Sero Glan",
    authorName: "Sero Glan",
    authorImage: "/images/author-04 (1).jpg",
    authorQuote: "“My books are marked down because most of them are marked with a on the edge by publishers.”",
    price: "£18.00",
    numericPrice: 18.0,
    category: "Biography",
    availability: "in-stock",
    image: "/images/book_section5.webp",
    coverId: "bestseller-5",
    summary:
      "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur erit qui in ea voluptate",
    description:
      "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    authorBooks: [
      {
        id: "bs-1",
        image: "/images/Newest5.webp",
        title: "Bulle und Pelle",
        oldPrice: "£50.00",
        price: "£28.00",
        badge: "SALE",
        slug: "bulle-und-pelle",
      },
      {
        id: "bs-2",
        image: "/images/book_section3.webp",
        title: "The Night Ocean",
        oldPrice: "£25.00",
        price: "£22.00",
        badge: "SALE",
        slug: "the-night-ocean",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/book_section7.webp",
        title: "Bulle & Pelle",
        author: "By SAVANNA WALKER",
        oldPrice: "£19.00",
        price: "£16.00",
        badge: "SALE_AND_HOT",
        badgeType: "sale",
        slug: "bulle-and-pelle",
      },
      {
        id: "rel-2",
        image: "/images/book_section2.png",
        title: "Peter and the Wolf",
        author: "By JOHN WALKER",
        oldPrice: "£40.00",
        price: "£22.00",
        badge: "SALE_AND_HOT",
        badgeType: "sale",
        slug: "peter-and-the-wolf",
      },
      {
        id: "rel-3",
        image: "/images/book_section4.webp",
        title: "The Assault",
        author: "By MESHO BUVAHR, SI MODARSK",
        price: "£19.00",
        slug: "the-assault",
      },
      {
        id: "rel-4",
        image: "/images/shop7.webp",
        title: "The Summer of Impossible Things",
        author: "By CHAI IAM, HOF NURGIN",
        price: "£20.00",
        slug: "the-summer-of-impossible-things",
      },
    ],
  },
  {
    id: "shop-9",
    slug: "ghosts-afraid-of-the-dark",
    title: "Ghost's Afraid of the Dark",
    author: "By Hof Nurgin, Mesho Buvahr",
    authorName: "Hof Nurgin",
    authorImage: "/images/author-03.jpg",
    authorQuote: "“My books are marked down because most of them are marked with a on the edge by publishers.”",
    price: "£16.00",
    numericPrice: 16.0,
    badge: "SALE",
    category: "For Kid",
    availability: "on-sale",
    image: "/images/shop8.jpg",
    coverId: "shop8",
    summary:
      "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur erit qui in ea voluptate",
    description:
      "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    authorBooks: [
      {
        id: "mb-1",
        image: "/images/Newest2.webp",
        title: "A Poem for Every night",
        price: "£22.00",
        slug: "a-poem-for-every-night",
      },
      {
        id: "mb-2",
        image: "/images/Newest4.webp",
        title: "Life of Pi",
        price: "£12.00",
        slug: "life-of-pi",
      },
      {
        id: "mb-3",
        image: "/images/shop2.jpg",
        title: "All this has nothing to do with Me",
        price: "£20.00",
        badge: "HOT",
        slug: "all-this-has-nothing-to-do-with-me",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/Newest4.webp",
        title: "Life of Pi",
        author: "By HANA KIM, HOF NURGIN",
        price: "£12.00",
        slug: "life-of-pi",
      },
      {
        id: "rel-2",
        image: "/images/Newest3.webp",
        title: "The Journey of Dreams",
        author: "By BHUZUN NAHLAM, JOHN WALKER",
        price: "£12.00",
        badge: "HOT",
        badgeType: "hot",
        slug: "the-journey-of-dreams",
      },
      {
        id: "rel-3",
        image: "/images/Newest1.webp",
        title: "Henry & The Good Dog",
        author: "By MESHO BUVAHR, SAVANNA WALKER",
        oldPrice: "£25.00",
        price: "£22.00",
        badge: "SALE",
        badgeType: "sale",
        slug: "henry-and-the-good-dog",
      },
      {
        id: "rel-4",
        image: "/images/shop5.jpg",
        title: "The Carrot Hunt",
        author: "By NOREEN HARRIS, MESHO BUVAHR",
        price: "£19.00",
        slug: "the-carrot-plan",
      },
    ],
  },
  {
    id: "shop-10",
    slug: "henry-and-the-good-dog",
    title: "Henry & The Good Dog",
    author: "By Mesho Buvahr, Savanna Walker",
    authorName: "Mesho Buvahr",
    authorImage: "/images/author-06 (1).jpg",
    authorQuote: "“My books are marked down because most of them are marked with a on the edge by publishers.”",
    price: "£22.00",
    originalPrice: "£25.00",
    numericPrice: 22.0,
    badge: "SALE",
    category: "For Kid",
    availability: "on-sale",
    image: "/images/Newest1.webp",
    coverId: "arrival-2",
    summary:
      "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur erit qui in ea voluptate",
    description:
      "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    authorBooks: [
      {
        id: "hd-1",
        image: "/images/shop5.jpg",
        title: "The Carrot Hunt",
        price: "£19.00",
        slug: "the-carrot-plan",
      },
      {
        id: "hd-2",
        image: "/images/shop4.jpg",
        title: "Dear Brain",
        oldPrice: "£18.00",
        price: "£14.00",
        badge: "SALE",
        slug: "dear-brain",
      },
      {
        id: "hd-3",
        image: "/images/book_section4.webp",
        title: "The Assault",
        price: "£19.00",
        slug: "the-assault",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/book_section3.webp",
        title: "The Night Ocean",
        author: "By SERO GLAN, SI MODARSK",
        oldPrice: "£25.00",
        price: "£22.00",
        badge: "SALE",
        badgeType: "sale",
        slug: "the-night-ocean",
      },
      {
        id: "rel-2",
        image: "/images/Newest4.webp",
        title: "Life of Pi",
        author: "By HANA KIM, HOF NURGIN",
        price: "£12.00",
        slug: "life-of-pi",
      },
      {
        id: "rel-3",
        image: "/images/Newest2.webp",
        title: "A Poem for Every night",
        author: "By CHAI IAM, HOF NURGIN",
        price: "£22.00",
        slug: "a-poem-for-every-night",
      },
      {
        id: "rel-4",
        image: "/images/shop8.jpg",
        title: "Ghost’s Afraid of the Dark",
        author: "By HOF NURGIN, MESHO BUVAHR",
        oldPrice: "£15.00",
        price: "£12.00",
        badge: "SALE",
        badgeType: "sale",
        slug: "ghosts-afraid-of-the-dark",
      },
    ],
  },
  {
    id: "shop-11",
    slug: "life-of-pi",
    title: "Life of Pi",
    author: "By Hana Kim, Hof Nurgin",
    authorName: "Hof Nurgin",
    authorImage: "/images/author-07.jpg",
    authorQuote: "“My books are marked down because most of them are marked with a on the edge by publishers.”",
    price: "£12.00",
    numericPrice: 12.0,
    category: "For Kid",
    availability: "in-stock",
    image: "/images/Newest4.webp",
    coverId: "arrival-5",
    summary:
      "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur erit qui in ea voluptate",
    description:
      "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    authorBooks: [
      {
        id: "lp-1",
        image: "/images/Newest2.webp",
        title: "A Poem for Every night",
        price: "£22.00",
        slug: "a-poem-for-every-night",
      },
      {
        id: "lp-2",
        image: "/images/shop2.jpg",
        title: "All this has nothing to do with Me",
        price: "£20.00",
        badge: "HOT",
        slug: "all-this-has-nothing-to-do-with-me",
      },
      {
        id: "lp-3",
        image: "/images/shop8.jpg",
        title: "Ghost’s Afraid of the Dark",
        oldPrice: "£15.00",
        price: "£12.00",
        badge: "SALE",
        slug: "ghosts-afraid-of-the-dark",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/book_section3.webp",
        title: "The Night Ocean",
        author: "By SERO GLAN, SI MODARSK",
        oldPrice: "£25.00",
        price: "£22.00",
        badge: "SALE",
        badgeType: "sale",
        slug: "the-night-ocean",
      },
      {
        id: "rel-2",
        image: "/images/shop5.jpg",
        title: "The Carrot Hunt",
        author: "By NOREEN HARRIS, MESHO BUVAHR",
        price: "£19.00",
        slug: "the-carrot-plan",
      },
      {
        id: "rel-3",
        image: "/images/shop2.jpg",
        title: "All this has nothing to do with Me",
        author: "By BHUZUN NAHLAM, HOF NURGIN",
        price: "£20.00",
        badge: "HOT",
        badgeType: "hot",
        slug: "all-this-has-nothing-to-do-with-me",
      },
      {
        id: "rel-4",
        image: "/images/shop8.jpg",
        title: "Ghost’s Afraid of the Dark",
        author: "By HOF NURGIN, MESHO BUVAHR",
        oldPrice: "£15.00",
        price: "£12.00",
        badge: "SALE",
        badgeType: "sale",
        slug: "ghosts-afraid-of-the-dark",
      },
    ],
  },
  {
    id: "shop-12",
    slug: "peter-and-the-wolf",
    title: "Peter and the Wolf",
    author: "By John Walker",
    authorName: "John Walker",
    authorImage: "/images/author-08 (1).jpg",
    authorQuote: "“My books are marked down because most of them are marked with a on the edge by publishers.”",
    price: "£22.00",
    originalPrice: "£40.00",
    numericPrice: 22.0,
    badge: "SALE_AND_HOT",
    category: "Biography",
    availability: "on-sale",
    image: "/images/book_section2.png",
    coverId: "bestseller-2",
    summary:
      "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur erit qui in ea voluptate",
    description:
      "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    authorBooks: [
      {
        id: "jw-1",
        image: "/images/Newest3.webp",
        title: "The Journey of Dreams",
        price: "£12.00",
        badge: "HOT",
        slug: "the-journey-of-dreams",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/book_section1.png",
        title: "The Journey of Visions toVictory",
        author: "By SANTOSH KUMAR MISHRA",
        price: "£35.00",
        slug: "the-journey-of-visions-to-victory",
      },
      {
        id: "rel-2",
        image: "/images/book_section5.webp",
        title: "Enemy — Jake Gyllenhaal",
        author: "By SERO GLAN",
        price: "£18.00",
        slug: "enemy-jake-gyllenhaal",
      },
      {
        id: "rel-3",
        image: "/images/shop7.webp",
        title: "The Summer of Impossible Things",
        author: "By CHAI IAM, HOF NURGIN",
        price: "£24.00",
        slug: "the-summer-of-impossible-things",
      },
      {
        id: "rel-4",
        image: "/images/book_section7.webp",
        title: "Bulle & Pelle",
        author: "By SAVANNA WALKER",
        oldPrice: "£19.00",
        price: "£16.00",
        badge: "SALE_AND_HOT",
        badgeType: "sale",
        slug: "bulle-and-pelle",
      },
      {
        id: "rel-5",
        image: "/images/book_section3.webp",
        title: "The Night Ocean",
        author: "By SERO GLAN, SI MODARSK",
        oldPrice: "£25.00",
        price: "£22.00",
        badge: "SALE",
        badgeType: "sale",
        slug: "the-night-ocean",
      },
      {
        id: "rel-6",
        image: "/images/book_section4.webp",
        title: "The Assault",
        author: "By MESHO BUVAHR, SI MODARSK",
        price: "£19.00",
        slug: "the-assault",
      },
    ],
  },
  {
    id: "shop-13",
    slug: "some-bodies-is-not-broken",
    title: "Some Bodies is Not Broken",
    author: "By STEPHANIE FOO",
    authorName: "Stephanie Foo",
    authorImage: "/images/author-02.jpg",
    authorQuote: "“Healing is not about erasing the scars; it is about building a life so vast that the scars become part of your strength.”",
    price: "£14.00",
    numericPrice: 14.0,
    badge: "SALE",
    category: "Fiction",
    availability: "on-sale",
    image: "/images/Newest6.webp",
    coverId: "arrival-6",
    summary:
      "A deeply moving memoir about healing complex trauma, embracing vulnerability, and discovering resilience and wholeness.",
    description:
      "Some Bodies is Not Broken is an unflinching, hopeful investigation into personal healing and generational triumph. Drawing on investigative journalism, scientific research, and raw memoirs, Stephanie Foo offers an unforgettable guide to emotional freedom.",
    authorBooks: [
      {
        id: "sf-1",
        image: "/images/book_section3.webp",
        title: "The Night Ocean",
        price: "£22.00",
        slug: "the-night-ocean",
      },
      {
        id: "sf-1",
        image: "/images/book_section4.webp",
        title: "The Assault",
        price: "£19.00",
        slug: "the-assault",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/shop9.jpg",
        title: "TRIO – Sarah Tolmie",
        author: "by Chai Iam, Savanna Walker",
        price: "£21.00",
        slug: "TRIO – Sarah Tolmie",
      },

    ],
  },
  {
    id: "shop-14",
    slug: "the-minds-mastery",
    title: "The Assault",
    author: "By MARCUS HATHAWAY",
    authorName: " Mesho Buvahr",
    authorImage: "/images/author-06 (1).jpg",
    authorQuote: "My books are marked down because most of them are marked with a on the edge by publishers.",
    price: "£13.00",
    numericPrice: 13.0,
    category: "Fiction",
    availability: "in-stock",
    image: "/images/book_section4.webp",
    coverId: "bestseller-4",
    summary:
      "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur erit qui in ea voluptate",
    description:
      "The Mind’s Mastery provides a powerful blueprint for mental clarity, discipline, and strategic calm. Marcus Hathaway combines classical stoicism with cutting-edge cognitive psychology to help you conquer distractions and master your craft.",
    authorBooks: [
      {
        id: "mh-1",
        image: "/images/Newest1.webp",
        title: "Henry & The Good Dog",
        price: "£12.00",
        slug: "Henry & The Good Dog",
      },
      {
        id: "mh-2",
        image: "/images/shop5.jpg",
        title: "The carrot Plan",
        price: "£19.00",
        slug: "the-carrot-Plan",
      },
      {
        id: "mh-2",
        image: "/images/shop4.jpg",
        title: "Dear Brain",
        price: "£18.00",
        slug: "Dear Brain",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/book_section7.webp",
        title: "Bulle & Pelle",
        author: "By SAVANNA WALKER",
        price: "£16.00",
        slug: "bulle-and-pelle",
      },
      {
        id: "rel-2",
        image: "/images/book_section2.png",
        title: "Peter and the Wolf",
        author: "By JOHN WALKER",
        price: "£12.00",
        slug: "peter-and-the-wolf",
      },
      {
        id: "rel-3",
        image: "/images/book_section3.webp",
        title: "The Night Ocean",
        author: "By SERO GLAN, SI MODARSK",
        price: "£22.00",
        slug: "the-night-ocean",
      },
      {
        id: "rel-4",
        image: "/images/book_section1.png",
        title: "The Journey of Visions to Victory",
        author: "By SANTOSH KUMAR MISHRA",
        price: "£35.00",
        slug: "the-journey-of-visions-to-victory",
      },
      {
        id: "rel-5",
        image: "/images/book_section8.webp",
        title: "The Summer of Impossible Things",
        author: "By CHAI IAM, HOF NURGIN",
        price: "£24.00",
        slug: "the-summer-of-impossible-things",
      },
      {
        id: "rel-6",
        image: "/images/book_section6.webp",
        title: "When the Doves Disappeared",
        author: "By HOF NURGIN",
        price: "£24.00",
        slug: "when-the-doves-disappeared",
      },
    ],
  },
  {
    id: "shop-15",
    slug: "the-carrot-plan",
    title: "The Carrot Hunt",
    author: "By NOREEN HARRIS",
    authorName: "Noreen Harris",
    authorImage: "/images/author-10.jpg",
    authorQuote: "“Great dreams grow from the smallest seeds of patience, kindness, and collaboration.”",
    price: "£15.00",
    numericPrice: 15.0,
    category: "Children's",
    availability: "in-stock",
    image: "/images/shop5.jpg",
    coverId: "shop5",
    summary:
      "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur erit qui in ea voluptate",
    description:
      "The Carrot Plan is an enchanting children's book following a clever family of woodland rabbits who band together to cultivate the most miraculous vegetable garden their forest has ever seen.",
    authorBooks: [
      {
        id: "nh-1",
        image: "/images/Newest1.webp",
        title: "Henry & The Good Dog",
        price: "£17.00",
        slug: "henry-and-the-good-dog",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/book_section1.png",
        title: "Sam & Dave Dig a Hole",
        author: "By MAC BARNETT",
        price: "£14.00",
        slug: "sam-and-dave-dig-a-hole",
      },
      {
        id: "rel-2",
        image: "/images/Newest1.webp",
        title: "Henry & The Good Dog",
        author: "By MESHO BUVAHR",
        price: "£17.00",
        slug: "henry-and-the-good-dog",
      },
      {
        id: "rel-3",
        image: "/images/Newest5.webp",
        title: "Bulle und Pelle",
        author: "By OSCAR OULLIÈRE",
        price: "£14.00",
        slug: "bulle-und-pelle",
      },
      {
        id: "rel-4",
        image: "/images/book_section3.webp",
        title: "Peter and the Wolf",
        author: "By SERGEI PROKOFIEV",
        price: "£16.00",
        slug: "peter-and-the-wolf",
      },
    ],
  },
  {
    id: "shop-16",
    slug: "the-dark",
    title: "The D.A.R.K",
    author: "By MESHO BUVAHR",
    authorName: "Mesho Buvahr",
    authorImage: "/images/author-02.jpg",
    authorQuote: "“My books are marked down because most of them are marked with a on the edge by publishers.”",
    price: "£18.00",
    numericPrice: 17.0,
    category: "Fiction",
    availability: "in-stock",
    image: "/images/shop6.jpg",
    coverId: "shop6",
    summary:
      "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur erit qui in ea voluptate",
    description:
      "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    authorBooks: [
      
      {
        id: "mb-3",
        image: "/images/Newest1.webp",
        title: "Henry & The Good Dog",
        price: "£22.00",
        slug: "Henry & The Good Dog",
      },
      {
        id: "mb-4",
        image: "/images/shop3.jpg",
        title: "Creative Life",
        price: "£16.00",
        slug: "Creative Life",
      },
      {
        id: "mb-5",
        image: "/images/shop1.jpg",
        title: "A Teaspoon of Earth and Sea",
        price: "£20.00",
        slug: "A Teaspoon of Earth and Sea",
      },
      {
        id: "mb-6",
        image: "/images/shop9.jpg",
        title: "TRIO - Sarah Tolmie",
        price: "£21.00",
        slug: "TRIO - Sarah Tolmie",
      },
      {
        id: "mb-7",
        image: "/images/book_section7.webp",
        title: "Bulle & Pelle",
        price: "£16.00",
        slug: "Bulle & Pelle",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/shop8.jpg",
        title: "Ghosts Around of the Dark",
        author: "By MESHO BUVAHR",
        price: "£16.00",
        slug: "ghosts-around-of-the-dark",
      },
      {
        id: "rel-2",
        image: "/images/book_section6.webp",
        title: "The Night I Died",
        author: "By HOF NURGIN",
        price: "£20.00",
        slug: "the-night-i-died",
      },
      {
        id: "rel-3",
        image: "/images/book_section5.webp",
        title: "Enemy — Jake Gyllenhaal",
        author: "By BRUCE SANG",
        price: "£18.00",
        slug: "enemy-jake-gyllenhaal",
      },
      {
        id: "rel-4",
        image: "/images/Newest4.webp",
        title: "Life of Pi",
        author: "By YANN MARTEL",
        price: "£16.00",
        slug: "life-of-pi",
      },
    ],
  },
  {
    id: "shop-17",
    slug: "the-journey-of-dreams",
    title: "The Journey of Dreams",
    author: "By BHUZUN NAHLAM, JOHN WALKER",
    authorName: "Bhuzun Nahlam",
    authorImage: "/images/author-03.jpg",
    authorQuote: "“My books are marked down because most of them are marked with a on the edge by publishers.”",
    price: "£12.00",
    numericPrice: 12.0,
    badge: "HOT",
    category: "For Kid",
    availability: "in-stock",
    image: "/images/Newest3.webp",
    coverId: "arrival-4",
    summary:
      "A poetic and inspiring fable about following destiny across mystical landscapes and unexpected friendships.",
    description:
      "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    authorBooks: [
      {
        id: "jd-1",
        image: "/images/shop2.jpg",
        title: "All this has nothing to do with Me",
        price: "£20.00",
        slug: "all-this-has-nothing-to-do-with-me",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/Newest1.webp",
        title: "Henry & The Good Dog",
        author: "By MESHO BUVAHR, SAVANNA WALKER",
        price: "£22.00",
        oldPrice: "£25.00",
        originalPrice: "£25.00",
        badge: "SALE",
        slug: "henry-and-the-good-dog",
      },
      {
        id: "rel-2",
        image: "/images/shop2.jpg",
        title: "All this has nothing to do with Me",
        author: "By BHUZUN NAHLAM, HOF NURGIN",
        price: "£20.00",
        badge: "HOT",
        slug: "all-this-has-nothing-to-do-with-me",
      },
      {
        id: "rel-3",
        image: "/images/book_section3.webp",
        title: "The Night Ocean",
        author: "By SERO GLAN, SI MODARSK",
        price: "£22.00",
        oldPrice: "£25.00",
        originalPrice: "£25.00",
        badge: "SALE",
        slug: "the-night-ocean",
      },
      {
        id: "rel-4",
        image: "/images/shop4.jpg",
        title: "Dear Brain",
        author: "By MESHO BUVAHR, TE SORKAZ",
        price: "£18.00",
        oldPrice: "£21.00",
        originalPrice: "£21.00",
        badge: "SALE",
        slug: "dear-brain",
      },
    ],
  },
  {
    id: "shop-18",
    slug: "the-journey-of-visions-to-victory",
    title: "The Journey of Visions to Victory",
    author: "By SANTOSH KUMAR MISHRA",
    authorName: "Santosh Kumar Mishra",
    authorImage: "/images/author-01.jpg",
    authorQuote: "“My books are written from the human soul of love, crafted with an aim to help readers triumph over every adversity.”",
    price: "£35.00",
    numericPrice: 35.0,
    category: "Fiction",
    availability: "in-stock",
    image: "/images/book_section1.png",
    coverId: "arrival-1",
    summary:
      "The definitive bestselling guide to turning ambitious dreams into triumphant realities and purposeful leadership.",
    description:
      "Visions of Victory chronicles the inspiring journey of overcoming insurmountable challenges, building resilience, and executing bold visions. A masterpiece filled with actionable wisdom, soulful encouragement, and transformative life strategies.",
    authorBooks: [
      {
        id: "vv-1",
        image: "/images/Newest3.webp",
        title: "The Journey of Dreams",
        price: "£12.00",
        slug: "the-journey-of-dreams",
      },
      {
        id: "vv-2",
        image: "/images/book_section8.webp",
        title: "The Summer of Impossible Things",
        price: "£24.00",
        slug: "the-summer-of-impossible-things",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/Newest3.webp",
        title: "The Journey of Dreams",
        author: "By BHUZUN NAHLAM",
        price: "£12.00",
        slug: "the-journey-of-dreams",
      },
      {
        id: "rel-2",
        image: "/images/book_section3.webp",
        title: "The Night Ocean",
        author: "By SERO GLAN, SI MODARSK",
        price: "£22.00",
        slug: "the-night-ocean",
      },
    ],
  },
  {
    id: "shop-19",
    slug: "the-night-ocean",
    title: "The Night Ocean",
    author: "By SERO GLAN, SI MODARSK",
    authorName: "Sero Glan & Si Modarsk",
    authorImage: "/images/author-02.jpg",
    authorQuote: "“My books are marked down because most of them are marked with a on the edge by publishers.”",
    price: "£22.00",
    originalPrice: "£25.00",
    numericPrice: 22.0,
    badge: "SALE",
    category: "Children's",
    availability: "on-sale",
    image: "/images/book_section3.webp",
    coverId: "arrival-8",
    summary:
      "A mysterious, labyrinthine journey through identity, lost manuscripts, and atmospheric literary secrets.",
    description:
      "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    authorBooks: [
      {
        id: "pw-1",
        image: "/images/book_section1.png",
        title: "Sam & Dave dig a Hole",
        author: "By MAC BARNETT",
        price: "£14.00",
        oldPrice: "£18.00",
        badge: "SALE",
        slug: "sam-and-dave-dig-a-hole",
      },
      {
        id: "pw-2",
        image: "/images/shop2.jpg",
        title: "The Assault",
        author: "By Harry Mulisch",
        price: "£19.00",
        slug: "all-this-has-nothing-to-do-with-me",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/shop4.jpg",
        title: "Dear Brain",
        author: "By MESHO BUVAHR, TE SORKAZ",
        price: "£13.00",
        oldPrice: "£16.00",
        badge: "SALE",
        badgeType: "sale",
        slug: "dear-brain",
      },
      {
        id: "rel-2",
        image: "/images/shop6.jpg",
        title: "The DARK",
        author: "By SAVANNA WALKER",
        price: "£18.00",
        slug: "the-dark",
      },
      {
        id: "rel-3",
        image: "/images/book_section5.webp",
        title: "Enemy — Jake Gyllenhaal",
        author: "By SERO GLAN",
        price: "£18.00",
        slug: "enemy-jake-gyllenhaal",
      },
      {
        id: "rel-4",
        image: "/images/Newest2.webp",
        title: "A Poem for Every night",
        author: "By CHAI IAM, HOF NURGIN",
        price: "£22.00",
        slug: "a-poem-for-every-night",
      },
    ],
  },
  {
    id: "shop-20",
    slug: "the-summer-of-impossible-things",
    title: "The Summer of Impossible Things",
    author: "By CHAI IAM, HOF NURGIN",
    authorName: "Chai Iam",
    authorImage: "/images/author-01.jpg",
    authorQuote: "“My books are marked down because most of them are marked with a on the edge by publishers.”",
    price: "£24.00",
    numericPrice: 24.0,
    category: "Fiction",
    availability: "in-stock",
    image: "/images/book_section8.webp",
    coverId: "bestseller-8",
    summary:
      "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur erit qui in ea voluptate",
    description:
      "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    authorBooks: [
      {
        id: "sb-1",
        image: "/images/Newest2.webp",
        title: "A Poem for Every night",
        price: "£22.00",
        slug: "a-poem-for-every-night",
      },
      {
        id: "sb-2",
        image: "/images/shop9.jpg",
        title: "TRIO – Sarah Tolmie",
        badge: "SALE_AND_HOT",
        oldPrice: "£24.00",
        price: "£21.00",
        slug: "trio-sarah-tolmie",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/book_section7.webp",
        title: "Bulle & Pelle",
        author: "By SAVANNA WALKER",
        badge: "SALE_AND_HOT",
        badgeType: "sale",
        oldPrice: "£18.00",
        price: "£16.00",
        slug: "bulle-and-pelle",
      },
      {
        id: "rel-2",
        image: "/images/book_section5.webp",
        title: "Enemy – Jake Gyllenhaal",
        author: "By SERO GLAN",
        price: "£18.00",
        slug: "enemy-jake-gyllenhaal",
      },
      {
        id: "rel-3",
        image: "/images/shop2.jpg",
        title: "The Assault",
        author: "By MESHO BUVAHR, SI MODARSK",
        price: "£18.00",
        slug: "all-this-has-nothing-to-do-with-me",
      },
      {
        id: "rel-4",
        image: "/images/book_section2.png",
        title: "Peter and the Wolf",
        author: "By JOHN WALKER",
        badge: "SALE_AND_HOT",
        badgeType: "sale",
        oldPrice: "£26.00",
        price: "£22.00",
        slug: "peter-and-the-wolf",
      },
    ],
  },
  {
    id: "shop-21",
    slug: "trio-sarah-tolmie",
    title: "TRIO – Sarah Tolmie",
    author: "By CHAI IAM, SAVANNA WALKER",
    authorName: "Chai Iam",
    authorImage: "/images/author-01.jpg",
    authorQuote: "“My books are marked down because most of them are marked with a on the edge by publishers.”",
    price: "£21.00",
    originalPrice: "£24.00",
    numericPrice: 21.0,
    badge: "SALE_AND_HOT",
    category: "Drama",
    availability: "on-sale",
    image: "/images/shop9.jpg",
    coverId: "shop9",
    summary:
      "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur erit qui in ea voluptate",
    description:
      "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    authorBooks: [
      {
        id: "tr-1",
        image: "/images/Newest2.webp",
        title: "A Poem for Every night",
        price: "£22.00",
        slug: "a-poem-for-every-night",
      },
      {
        id: "tr-2",
        image: "/images/book_section8.webp",
        title: "The Summer of Impossible Things",
        price: "£24.00",
        slug: "the-summer-of-impossible-things",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/book_section1.png",
        title: "Sam & Dave dig a Hole",
        author: "By SI MODARSK, TE SORKAZ",
        badge: "SALE",
        badgeType: "sale",
        oldPrice: "£18.00",
        price: "£14.00",
        slug: "sam-and-dave-dig-a-hole",
      },
    ],
  },
  {
    id: "shop-22",
    slug: "when-the-doves-disappeared",
    title: "When the Doves disappeared",
    author: "By HOF NURGIN",
    authorName: "Hof Nurgin",
    authorImage: "/images/author-07.jpg",
    authorQuote: "“My books are marked down because most of them are marked with a on the edge by publishers.”",
    price: "£24.00",
    numericPrice: 24.0,
    category: "Biography",
    availability: "in-stock",
    image: "/images/book_section6.webp",
    coverId: "bestseller-6",
    summary:
      "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur erit qui in ea voluptate",
    description:
      "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    authorBooks: [
      {
        id: "wd-1",
        image: "/images/Newest2.webp",
        title: "A Poem for Every night",
        price: "£22.00",
        slug: "a-poem-for-every-night",
      },
      {
        id: "wd-2",
        image: "/images/Newest4.webp",
        title: "Life of PI",
        price: "£12.00",
        slug: "life-of-pi",
      },
      {
        id: "wd-3",
        image: "/images/shop2.jpg",
        title: "All this has nothing to do with Me",
        badge: "HOT",
        price: "£20.00",
        slug: "all-this-has-nothing-to-do-with-me",
      },
      {
        id: "wd-4",
        image: "/images/shop8.jpg",
        title: "Ghost's Afraid of the Dark",
        badge: "SALE",
        oldPrice: "£16.00",
        price: "£12.00",
        slug: "ghosts-afraid-of-the-dark",
      },
      {
        id: "wd-5",
        image: "/images/book_section8.webp",
        title: "The Summer of Impossible Things",
        price: "£24.00",
        slug: "the-summer-of-impossible-things",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/book_section3.webp",
        title: "The Night Ocean",
        author: "By SERO GLAN, SI MODARSK",
        badge: "SALE",
        badgeType: "sale",
        oldPrice: "£25.00",
        price: "£22.00",
        slug: "the-night-ocean",
      },
      {
        id: "rel-2",
        image: "/images/book_section4.webp",
        title: "The Assault",
        author: "By MESHO BUVAHR, SI MODARSK",
        price: "£19.00",
        slug: "the-assault",
      },
      {
        id: "rel-3",
        image: "/images/book_section1.png",
        title: "The Journey of Visions to Victory",
        author: "By SANTOSH KUMAR MISHRA",
        price: "£35.00",
        slug: "the-journey-of-visions-to-victory",
      },
      {
        id: "rel-4",
        image: "/images/book_section5.webp",
        title: "Enemy – Jake Gyllenhaal",
        author: "By SERO GLAN",
        price: "£18.00",
        slug: "enemy-jake-gyllenhaal",
      },
    ],
  },
  {
    id: "shop-23",
    slug: "the-summer-of-impossible-things",
    title: "The Summer of Impossible Things",
    author: "By CHAI IAM, HOF NURGIN",
    authorName: "Chai Iam",
    authorImage: "/images/author-01.jpg",
    authorQuote: "“My books are marked down because most of them are marked with a on the edge by publishers.”",
    price: "£24.00",
    numericPrice: 24.0,
    category: "Fiction",
    availability: "in-stock",
    image: "/images/shop7.webp",
    coverId: "bestseller-8",
    summary:
      "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur erit qui in ea voluptate",
    description:
      "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    authorBooks: [
      {
        id: "sb-1",
        image: "/images/Newest2.webp",
        title: "A Poem for Every night",
        price: "£22.00",
        slug: "a-poem-for-every-night",
      },
      {
        id: "sb-2",
        image: "/images/shop9.jpg",
        title: "TRIO – Sarah Tolmie",
        badge: "SALE_AND_HOT",
        oldPrice: "£24.00",
        price: "£21.00",
        slug: "trio-sarah-tolmie",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/book_section7.webp",
        title: "Bulle & Pelle",
        author: "By SAVANNA WALKER",
        badge: "SALE_AND_HOT",
        badgeType: "sale",
        oldPrice: "£18.00",
        price: "£16.00",
        slug: "bulle-and-pelle",
      },
      {
        id: "rel-2",
        image: "/images/book_section5.webp",
        title: "Enemy – Jake Gyllenhaal",
        author: "By SERO GLAN",
        price: "£18.00",
        slug: "enemy-jake-gyllenhaal",
      },
      {
        id: "rel-3",
        image: "/images/shop2.jpg",
        title: "The Assault",
        author: "By MESHO BUVAHR, SI MODARSK",
        price: "£18.00",
        slug: "all-this-has-nothing-to-do-with-me",
      },
      {
        id: "rel-4",
        image: "/images/book_section2.png",
        title: "Peter and the Wolf",
        author: "By JOHN WALKER",
        badge: "SALE_AND_HOT",
        badgeType: "sale",
        oldPrice: "£26.00",
        price: "£22.00",
        slug: "peter-and-the-wolf",
      },
    ],
  },
  {
    id: "shop-24",
    slug: "trio-sarah-tolmie",
    title: "TRIO – Sarah Tolmie",
    author: "By CHAI IAM, SAVANNA WALKER",
    authorName: "Chai Iam",
    authorImage: "/images/author-01.jpg",
    authorQuote: "“My books are marked down because most of them are marked with a on the edge by publishers.”",
    price: "£21.00",
    originalPrice: "£24.00",
    numericPrice: 21.0,
    badge: "SALE_AND_HOT",
    category: "Drama",
    availability: "on-sale",
    image: "/images/shop9.jpg",
    coverId: "shop9",
    summary:
      "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur erit qui in ea voluptate",
    description:
      "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    authorBooks: [
      {
        id: "tr-1",
        image: "/images/Newest2.webp",
        title: "A Poem for Every night",
        price: "£22.00",
        slug: "a-poem-for-every-night",
      },
      {
        id: "tr-2",
        image: "/images/book_section8.webp",
        title: "The Summer of Impossible Things",
        price: "£24.00",
        slug: "the-summer-of-impossible-things",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/shop7.webp",
        title: "Sam & Dave dig a Hole",
        author: "By SI MODARSK, TE SORKAZ",
        badge: "SALE",
        badgeType: "sale",
        oldPrice: "£14.00",
        price: "£14.00",
        slug: "sam-and-dave-dig-a-hole",
      },
    ],
  },
  {
    id: "shop-25",
    slug: "the-journey-of-a-young-entrepreneur",
    title: "The Journey of a Young Entrepreneur",
    author: "By Santosh Kumar",
    authorName: "Santosh Kumar",
    authorImage: "/images/Gemini_Generated_Image_f41einf41einf41e.png",
    authorQuote: "“Every visionary journey begins with the audacity to dream and the courage to persist.”",
    price: "£18.00",
    oldPrice: "£22.00",
    numericPrice: 18.0,
    badge: "SALE",
    category: "Business",
    availability: "on-sale",
    image: "/images/book_section1.png",
    coverId: "bestseller-1",
    summary:
      "An inspiring, real-world roadmap detailing how relentless determination and creative leadership build monumental success.",
    description:
      "The Journey of a Young Entrepreneur is an acclaimed biographical account and practical manual for trailblazers, dreamers, and leaders. It uncovers pivotal moments of risk, resilience, and triumph in modern industry.",
    authorBooks: [
      {
        id: "jk-1",
        image: "/images/Newest3.webp",
        title: "Visions of Victory",
        price: "£19.00",
        slug: "visions-of-victory",
      },
      {
        id: "jk-2",
        image: "/images/book_section4.webp",
        title: "The Mind’s Mastery",
        price: "£13.00",
        slug: "the-minds-mastery",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/Newest3.webp",
        title: "Visions of Victory",
        author: "By SAVANNA WALKER",
        price: "£19.00",
        slug: "visions-of-victory",
      },
      {
        id: "rel-2",
        image: "/images/book_section4.webp",
        title: "The Mind’s Mastery",
        author: "By MARCUS HATHAWAY",
        price: "£13.00",
        slug: "the-minds-mastery",
      },
      {
        id: "rel-3",
        image: "/images/shop3.jpg",
        title: "Creative Life",
        author: "By DORCAS CHENG-TOZUN",
        price: "£13.00",
        slug: "creative-life",
      },
      {
        id: "rel-4",
        image: "/images/book_section2.png",
        title: "Dreams of the War",
        author: "By SUN TZU",
        price: "£18.00",
        slug: "dreams-of-the-war",
      },
    ],
  },
  {
    id: "shop-26",
    slug: "fragments-of-war",
    title: "Fragments of War",
    author: "By John Walker",
    authorName: "John Walker",
    authorImage: "/images/author-01.jpg",
    authorQuote: "“In the fragments of conflict, we uncover the enduring value of human solidarity and peace.”",
    price: "£18.00",
    oldPrice: "£24.00",
    numericPrice: 18.0,
    badge: "SALE",
    category: "Fiction",
    availability: "on-sale",
    image: "/images/book_section2.png",
    coverId: "bestseller-2",
    summary:
      "A deeply moving historical narrative capturing forgotten tales of bravery, survival, and brotherhood.",
    description:
      "Fragments of War paints a poignant, visceral portrait of human lives disrupted by global conflict. Through intertwined letters, diaries, and battlefield accounts, John Walker crafts an unforgettable testament to the human spirit.",
    authorBooks: [
      {
        id: "jw-1",
        image: "/images/book_section2.png",
        title: "Dreams of the War",
        price: "£18.00",
        slug: "dreams-of-the-war",
      },
      {
        id: "jw-2",
        image: "/images/book_section6.webp",
        title: "The Night I Died",
        price: "£20.00",
        slug: "the-night-i-died",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/book_section2.png",
        title: "Dreams of the War",
        author: "By SUN TZU",
        price: "£18.00",
        slug: "dreams-of-the-war",
      },
      {
        id: "rel-2",
        image: "/images/book_section5.webp",
        title: "Enemy — Jake Gyllenhaal",
        author: "By BRUCE SANG",
        price: "£18.00",
        slug: "enemy-jake-gyllenhaal",
      },
      {
        id: "rel-3",
        image: "/images/book_section6.webp",
        title: "The Night I Died",
        author: "By HOF NURGIN",
        price: "£20.00",
        slug: "the-night-i-died",
      },
      {
        id: "rel-4",
        image: "/images/Newest4.webp",
        title: "Life of Pi",
        author: "By YANN MARTEL",
        price: "£16.00",
        slug: "life-of-pi",
      },
    ],
  },
  {
    id: "shop-27",
    slug: "enemy-of-the-quiet-mind",
    title: "Enemy of the Quiet Mind",
    author: "By Alexander Kent",
    authorName: "Alexander Kent",
    authorImage: "/images/author-01.jpg",
    authorQuote: "“To conquer the noise of the outside world, first calm the internal turbulence.”",
    price: "£21.00",
    numericPrice: 21.0,
    category: "Fiction",
    availability: "in-stock",
    image: "/images/book_section5.webp",
    coverId: "bestseller-5",
    summary:
      "A compelling psychological study exploring modern anxiety, inner turmoil, and paths to serenity.",
    description:
      "Enemy of the Quiet Mind explores the unrelenting pressures of digital modern life and outlines transformative mental models to reclaim focus, peace, and purposeful living.",
    authorBooks: [
      {
        id: "ak-1",
        image: "/images/book_section4.webp",
        title: "The Mind’s Mastery",
        price: "£13.00",
        slug: "the-minds-mastery",
      },
      {
        id: "ak-2",
        image: "/images/shop4.jpg",
        title: "Dear Brain",
        price: "£14.00",
        slug: "dear-brain",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/book_section4.webp",
        title: "The Mind’s Mastery",
        author: "By MARCUS HATHAWAY",
        price: "£13.00",
        slug: "the-minds-mastery",
      },
      {
        id: "rel-2",
        image: "/images/shop4.jpg",
        title: "Dear Brain",
        author: "By NEDRA GLOVER TAWWAB",
        price: "£14.00",
        slug: "dear-brain",
      },
      {
        id: "rel-3",
        image: "/images/shop3.jpg",
        title: "Creative Life",
        author: "By DORCAS CHENG-TOZUN",
        price: "£13.00",
        slug: "creative-life",
      },
      {
        id: "rel-4",
        image: "/images/book_section6.webp",
        title: "The Night I Died",
        author: "By HOF NURGIN",
        price: "£20.00",
        slug: "the-night-i-died",
      },
    ],
  },
  {
    id: "shop-28",
    slug: "wounds-down-wisdom-up",
    title: "Wounds Down, Wisdom Up",
    author: "By Olivia Hart",
    authorName: "Olivia Hart",
    authorImage: "/images/author-02.jpg",
    authorQuote: "“Every setback carries within it the seed of an equivalent or greater blessing.”",
    price: "£19.00",
    numericPrice: 19.0,
    category: "Non-fiction",
    availability: "in-stock",
    image: "/images/book_section6.webp",
    coverId: "bestseller-6",
    summary:
      "A compassionate, practical guide for transforming personal grief and adversity into wisdom and strength.",
    description:
      "Wounds Down, Wisdom Up provides a warm and empowering roadmap for healing. Olivia Hart guides readers through self-discovery, forgiveness, and building renewed confidence following life's toughest chapters.",
    authorBooks: [
      {
        id: "oh-1",
        image: "/images/shop4.jpg",
        title: "Dear Brain",
        price: "£14.00",
        slug: "dear-brain",
      },
      {
        id: "oh-2",
        image: "/images/Newest6.webp",
        title: "Some Bodies is Not Broken",
        price: "£14.00",
        slug: "some-bodies-is-not-broken",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/shop4.jpg",
        title: "Dear Brain",
        author: "By NEDRA GLOVER TAWWAB",
        price: "£14.00",
        slug: "dear-brain",
      },
      {
        id: "rel-2",
        image: "/images/Newest6.webp",
        title: "Some Bodies is Not Broken",
        author: "By STEPHANIE FOO",
        price: "£14.00",
        slug: "some-bodies-is-not-broken",
      },
      {
        id: "rel-3",
        image: "/images/shop3.jpg",
        title: "Creative Life",
        author: "By DORCAS CHENG-TOZUN",
        price: "£13.00",
        slug: "creative-life",
      },
      {
        id: "rel-4",
        image: "/images/book_section8.webp",
        title: "A Sense of Wonder",
        author: "By SAVANNA WALKER",
        price: "£21.00",
        slug: "a-sense-of-wonder",
      },
    ],
  },
  {
    id: "shop-29",
    slug: "built-and-broken",
    title: "Built & Broken",
    author: "By Sophie Collins",
    authorName: "Sophie Collins",
    authorImage: "/images/author-02.jpg",
    authorQuote: "“To build something that lasts, one must first understand what it feels like to fall apart.”",
    price: "£18.00",
    numericPrice: 18.0,
    badge: "SALE",
    category: "Fiction",
    availability: "on-sale",
    image: "/images/book_section7.webp",
    coverId: "bestseller-7",
    summary:
      "A fast-paced, multi-generational saga of ambition, family empires, and emotional resilience.",
    description:
      "Built & Broken follows the rise and fall of an architectural dynasty across four decades. Rich with drama, secrets, and soaring ambition, this novel explores what we build in the world and what we leave behind.",
    authorBooks: [
      {
        id: "sc-1",
        image: "/images/shop1.jpg",
        title: "A Teaspoon of Earth and Sea",
        price: "£20.00",
        slug: "a-teaspoon-of-earth-and-sea",
      },
      {
        id: "sc-2",
        image: "/images/shop7.webp",
        title: "The Summer of Impossible Things",
        price: "£24.00",
        slug: "the-summer-of-impossible-things",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/shop1.jpg",
        title: "A Teaspoon of Earth and Sea",
        author: "By Dina Nayeri",
        price: "£20.00",
        slug: "a-teaspoon-of-earth-and-sea",
      },
      {
        id: "rel-2",
        image: "/images/shop7.webp",
        title: "The Summer of Impossible Things",
        author: "By Ethan Morris",
        price: "£24.00",
        slug: "the-summer-of-impossible-things",
      },
      {
        id: "rel-3",
        image: "/images/shop2.jpg",
        title: "All this has nothing to do with Me",
        author: "By BHUZUN NAHLAM",
        price: "£20.00",
        slug: "all-this-has-nothing-to-do-with-me",
      },
      {
        id: "rel-4",
        image: "/images/Newest3.webp",
        title: "Visions of Victory",
        author: "By SAVANNA WALKER",
        price: "£19.00",
        slug: "visions-of-victory",
      },
    ],
  },
  {
    id: "shop-30",
    slug: "peter-and-the-wolf",
    title: "Peter and the Wolf",
    author: "By SERO GLAN, SI MODARSK",
    authorName: "Sero Glan",
    authorImage: "/images/author-01.jpg",
    authorQuote: "“Stories create windows into unknown worlds where bravery and music conquer fear.”",
    price: "£14.00",
    numericPrice: 14.0,
    badge: "SALE",
    category: "Fiction",
    availability: "in-stock",
    image: "/images/Newest7.webp",
    coverId: "peter-and-the-wolf",
    summary:
      "A classic and captivating musical tale following young Peter and his woodland companions.",
    description:
      "Peter and the Wolf tells the thrilling story of courage and resourcefulness in the quiet countryside, bringing classic storytelling to life with timeless charm.",
    authorBooks: [
      {
        id: "jd-1",
        image: "/images/shop2.jpg",
        title: "All this has nothing to do with Me",
        price: "£20.00",
        slug: "all-this-has-nothing-to-do-with-me",
      },
      {
        id: "jd-2",
        image: "/images/Newest2.webp",
        title: "A Poem for Every Night",
        price: "£22.00",
        slug: "a-poem-for-every-night",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/shop2.jpg",
        title: "All this has nothing to do with Me",
        author: "By BHUZUN NAHLAM",
        price: "£20.00",
        slug: "all-this-has-nothing-to-do-with-me",
      },
      {
        id: "rel-2",
        image: "/images/Newest2.webp",
        title: "A Poem for Every Night",
        author: "By CHAI IAM",
        price: "£22.00",
        slug: "a-poem-for-every-night",
      },
      {
        id: "rel-3",
        image: "/images/shop1.jpg",
        title: "A Teaspoon of Earth and Sea",
        author: "By Dina Nayeri",
        price: "£20.00",
        slug: "a-teaspoon-of-earth-and-sea",
      },
      {
        id: "rel-4",
        image: "/images/Newest4.webp",
        title: "Life of Pi",
        author: "By YANN MARTEL",
        price: "£16.00",
        slug: "life-of-pi",
      },
    ],
  },
  {
    id: "shop-31",
    slug: "the-journey-of-visions-to-victory",
    title: "The Journey of Visions to Victory",
    author: "By SANTOSH KUMAR MISHRA",
    authorName: "Santosh Kumar Mishra",
    authorImage: "/images/Gemini_Generated_Image_f41einf41einf41e.png",
    authorQuote: "“My books are written from the human soul of love, are crafted with an aim to help readers by publisher.”",
    price: "£35.00",
    numericPrice: 35.0,
    category: "Business",
    availability: "in-stock",
    image: "/images/hero_section2.png",
    coverId: "arrival-1",
    summary:
      "The premier hardcover collector's edition of Santosh Kumar's celebrated guide to victory, leadership, and visionary execution.",
    description:
      "The Journey of Visions to Victory is an extraordinary masterwork combining biography, strategic philosophy, and profound life lessons. Bound in deluxe green and gold foil hardcover.",
    authorBooks: [
      {
        id: "jvv-1",
        image: "/images/Newest3.webp",
        title: "Visions of Victory",
        price: "£19.00",
        slug: "visions-of-victory",
      },
      {
        id: "jvv-2",
        image: "/images/book_section1.png",
        title: "The Journey of a Young Entrepreneur",
        price: "£18.00",
        slug: "the-journey-of-a-young-entrepreneur",
      },
    ],
    relatedBooks: [
      {
        id: "rel-1",
        image: "/images/Newest3.webp",
        title: "Visions of Victory",
        author: "By SAVANNA WALKER",
        price: "£19.00",
        slug: "visions-of-victory",
      },
      {
        id: "rel-2",
        image: "/images/book_section1.png",
        title: "The Journey of a Young Entrepreneur",
        author: "By Santosh Kumar",
        price: "£18.00",
        slug: "the-journey-of-a-young-entrepreneur",
      },
      {
        id: "rel-3",
        image: "/images/book_section4.webp",
        title: "The Mind’s Mastery",
        author: "By MARCUS HATHAWAY",
        price: "£13.00",
        slug: "the-minds-mastery",
      },
      {
        id: "rel-4",
        image: "/images/shop3.jpg",
        title: "Creative Life",
        author: "By DORCAS CHENG-TOZUN",
        price: "£13.00",
        slug: "creative-life",
      },
    ],
  },
];

// Map lookup helpers
const SLUG_MAP = new Map<string, BookDetailData>();
ALL_BOOKS_DATABASE.forEach((b) => {
  if (b.slug) SLUG_MAP.set(b.slug, b);
  // Also register variants
  const rawSlug = slugify(b.title);
  if (!SLUG_MAP.has(rawSlug)) SLUG_MAP.set(rawSlug, b);
  if (b.id) SLUG_MAP.set(b.id.toLowerCase(), b);
});

// Extra alias mappings
SLUG_MAP.set("the-journey-of-dreams", SLUG_MAP.get("shop-17")!);
SLUG_MAP.set("the-journey-of-visions-to-victory", SLUG_MAP.get("the-journey-of-visions-to-victory") || SLUG_MAP.get("shop-18")!);
SLUG_MAP.set("the-night-ocean", SLUG_MAP.get("the-night-ocean") || SLUG_MAP.get("peter-and-the-wolf")!);
SLUG_MAP.set("henry-the-good-dog", SLUG_MAP.get("henry-and-the-good-dog")!);
SLUG_MAP.set("henry-good-dog", SLUG_MAP.get("henry-and-the-good-dog")!);
SLUG_MAP.set("ghosts-around-of-the-dark", SLUG_MAP.get("ghosts-afraid-of-the-dark")!);
SLUG_MAP.set("dreams-of-the-war", SLUG_MAP.get("peter-and-the-wolf")!);
SLUG_MAP.set("visions-to-victory", SLUG_MAP.get("the-journey-of-visions-to-victory") || SLUG_MAP.get("visions-of-victory")!);

export function getBookBySlug(slug: string): BookDetailData {
  const cleanSlug = slug.toLowerCase().trim();
  if (SLUG_MAP.has(cleanSlug)) {
    return SLUG_MAP.get(cleanSlug)!;
  }

  // Try matching normalized title
  const found = ALL_BOOKS_DATABASE.find(
    (b) =>
      slugify(b.title) === cleanSlug ||
      (b.slug && cleanSlug.includes(b.slug)) ||
      cleanSlug.includes(slugify(b.title))
  );
  if (found) return found;

  // Graceful fallback for any unknown slug
  const titleWords = slug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");

  return {
    slug: cleanSlug,
    title: titleWords || "Featured Book Collection",
    author: "Publishing Hub Author",
    authorName: "Distinguished Author",
    authorImage: "/images/author-01.jpg",
    authorQuote: "“Every book is a passport to new horizons and timeless wisdom.”",
    price: "£20.00",
    numericPrice: 20.0,
    category: "Literature",
    availability: "in-stock",
    image: "/images/Newest2.webp",
    summary:
      "A masterpiece of contemporary storytelling, exploring timeless themes of courage, introspection, and human emotion.",
    description:
      "This exceptional edition is printed on premium acid-free paper with fine binding and archival quality craftsmanship. Designed to inspire and enrich your personal library for years to come.",
    authorBooks: [
      {
        id: "fb-1",
        image: "/images/Newest2.webp",
        title: "A Poem for Every Night",
        price: "£22.00",
        slug: "a-poem-for-every-night",
      },
      {
        id: "fb-2",
        image: "/images/shop1.jpg",
        title: "A Teaspoon of Earth and Sea",
        price: "£20.00",
        slug: "a-teaspoon-of-earth-and-sea",
      },
    ],
    relatedBooks: [
      {
        id: "fr-1",
        image: "/images/shop7.webp",
        title: "The Summer of Impossible Things",
        author: "By Ethan Morris",
        price: "£24.00",
        slug: "the-summer-of-impossible-things",
      },
      {
        id: "fr-2",
        image: "/images/Newest1.webp",
        title: "Henry & The Good Dog",
        author: "By Mesho Buvahr",
        price: "£17.00",
        slug: "henry-and-the-good-dog",
      },
      {
        id: "fr-3",
        image: "/images/shop9.jpg",
        title: "TRIO - Sarah Tolmie",
        author: "By Sarah Tolmie",
        price: "£21.00",
        slug: "trio-sarah-tolmie",
      },
      {
        id: "fr-4",
        image: "/images/Newest3.webp",
        title: "Visions of Victory",
        author: "By Savanna Walker",
        price: "£19.00",
        slug: "visions-of-victory",
      },
    ],
  };
}

export function getAllBooks(): BookDetailData[] {
  return ALL_BOOKS_DATABASE;
}

export function getBookSlug(book: { slug?: string; title?: string; id?: string }): string {
  if (book.slug) return book.slug;
  if (book.title) return slugify(book.title);
  if (book.id) return slugify(book.id);
  return "book";
}
