import { MeetTheAuthorProfileData } from "@/types/meetTheAuthor";

export const DEFAULT_MEET_THE_AUTHOR_PROFILES: MeetTheAuthorProfileData[] = [
  {
    id: "default",
    authorName: "Savanna Walker",
    authorImage: "/images/author-02.jpg",
    quote: "My books are marked down because most of them are marked with a on the edge by publishers.",
    facebook: "#facebook",
    twitter: "#twitter",
    linkedin: "#linkedin",
    instagram: "#instagram",
    books: [
      {
        id: "cmtr3nv6o0008muxzvahiqbxf",
        title: "Henry & The Good Dog",
        author: "By Mesho Buvahr, Savanna Walker",
        price: "£22.00",
        oldPrice: "£25.00",
        image: "/images/Newest1.webp",
        slug: "henry-and-the-good-dog",
        badge: "SALE",
        order: 0,
      },
      {
        id: "cmtr3nv5p0004muxzqpveh7po",
        title: "Creative Life",
        author: "By Hana Kim, Savanna Walker",
        price: "£18.00",
        image: "/images/shop3.jpg",
        slug: "creative-life",
        badge: "HOT",
        order: 1,
      },
      {
        id: "cmtr3nv80000emuxz51udisyh",
        title: "The D.A.R.K",
        author: "By MESHO BUVAHR",
        price: "£18.00",
        image: "/images/shop6.jpg",
        slug: "the-dark",
        order: 2,
      },
      {
        id: "cmtr3nv4n0000muxz7b0ojcw7",
        title: "A Teaspoon of Earth and Sea",
        author: "By Savanna Walker, Shia Ung",
        price: "£20.00",
        image: "/images/shop1.jpg",
        slug: "a-teaspoon-of-earth-and-sea",
        order: 3,
      },
    ],
  },
  {
    id: "mta_1789020597153_3nrt",
    authorName: "Shia Ung",
    authorImage: "/images/author-12.jpg",
    quote: "My books are marked down because most of them are marked with a on the edge by publishers.",
    facebook: "#facebook",
    twitter: "#twitter",
    linkedin: "#linkedin",
    instagram: "#instagram",
    books: [
      {
        id: "cmtr3nv5h0003muxzkl31b7s6",
        title: "Bulle und Pelle",
        author: "By Sero Glan, Shia Ung",
        price: "£28.00",
        image: "/images/Newest5.webp",
        slug: "bulle-und-pelle",
        badge: "SALE",
        order: 0,
      },
      {
        id: "cmtr3nv4n0000muxz7b0ojcw7",
        title: "A Teaspoon of Earth and Sea",
        author: "By Savanna Walker, Shia Ung",
        price: "£20.00",
        image: "/images/shop1.jpg",
        slug: "a-teaspoon-of-earth-and-sea",
        order: 1,
      },
    ],
  },
  {
    id: "mta_1789020338553_oulk",
    authorName: "Bhuzun Nahlam",
    authorImage: "/images/author-03.jpg",
    quote: "My books are marked down because most of them are marked with a on the edge by publishers.",
    facebook: "#facebook",
    twitter: "#twitter",
    linkedin: "#linkedin",
    instagram: "#instagram",
    books: [
      {
        id: "cmtr3nv89000fmuxz1vjzsasf",
        title: "The Journey of Dreams",
        author: "By BHUZUN NAHLAM, JOHN WALKER",
        price: "£12.00",
        image: "/images/Newest3.webp",
        slug: "the-journey-of-dreams",
        badge: "HOT",
        order: 0,
      },
      {
        id: "cmtr3nv4y0001muxzkzm5ephh",
        title: "All this has nothing to do with Me",
        author: "By BHUZUN NAHLAM, HOF NURGIN",
        price: "£20.00",
        image: "/images/shop2.jpg",
        slug: "all-this-has-nothing-to-do-with-me",
        badge: "HOT",
        order: 1,
      },
    ],
  },
  {
    id: "mta_1789019925144_rjcl",
    authorName: "Chai Iam",
    authorImage: "/images/author-01.jpg",
    quote: "My books are marked down because most of them are marked with a on the edge by publishers.",
    facebook: "#facebook",
    twitter: "#twitter",
    linkedin: "#linkedin",
    instagram: "#instagram",
    books: [
      {
        id: "cmtv4vwv60000gzjjhqaot6t2",
        title: "A Poem for Every Night",
        author: "By CHAI IAM, HOF NURGIN",
        price: "£22.00",
        image: "/images/Newest2.webp",
        slug: "a-poem-for-every-night",
        order: 0,
      },
      {
        id: "cmtr3nv95000jmuxzzz83wkb5",
        title: "TRIO – Sarah Tolmie",
        author: "By CHAI IAM, SAVANNA WALKER",
        price: "£21.00",
        oldPrice: "£24.00",
        image: "/images/shop9.jpg",
        slug: "trio-sarah-tolmie",
        badge: "SALE_AND_HOT",
        order: 1,
      },
      {
        id: "cmtr3nv8y000imuxzlxfnidu7",
        title: "The Summer of Impossible Things",
        author: "By CHAI IAM, HOF NURGIN",
        price: "£24.00",
        image: "/images/shop7.webp",
        slug: "the-summer-of-impossible-things",
        order: 2,
      },
    ],
  },
  {
    id: "mta_1789019925289_cqtb",
    authorName: "Hana Kim",
    authorImage: "/images/author-05.jpg",
    quote: "My books are marked down because most of them are marked with a on the edge by publishers.",
    facebook: "#facebook",
    twitter: "#twitter",
    linkedin: "#linkedin",
    instagram: "#instagram",
    books: [
      {
        id: "cmtr3nv6w0009muxzoifrfetx",
        title: "Life of Pi",
        author: "By Hana Kim, Hof Nurgin",
        price: "£12.00",
        image: "/images/Newest4.webp",
        slug: "life-of-pi",
        order: 0,
      },
      {
        id: "cmtr3nv5p0004muxzqpveh7po",
        title: "Creative Life",
        author: "By Hana Kim, Savanna Walker",
        price: "£18.00",
        image: "/images/shop3.jpg",
        slug: "creative-life",
        badge: "HOT",
        order: 1,
      },
    ],
  },
  {
    id: "mta_1789019925162_jn2c",
    authorName: "Hof Nurgin",
    authorImage: "/images/author-07.jpg",
    quote: "Acclaimed author of visionary literature and transformative storytelling.",
    facebook: "#facebook",
    twitter: "#twitter",
    linkedin: "#linkedin",
    instagram: "#instagram",
    books: [
      {
        id: "cmtr3nv6w0009muxzoifrfetx",
        title: "Life of Pi",
        author: "By Hana Kim, Hof Nurgin",
        price: "£12.00",
        image: "/images/Newest4.webp",
        slug: "life-of-pi",
        order: 0,
      },
      {
        id: "cmtr3nv4y0001muxzkzm5ephh",
        title: "All this has nothing to do with Me",
        author: "By BHUZUN NAHLAM, HOF NURGIN",
        price: "£20.00",
        image: "/images/shop2.jpg",
        slug: "all-this-has-nothing-to-do-with-me",
        badge: "HOT",
        order: 1,
      },
      {
        id: "cmtr3nv6d0007muxzamjlu4vi",
        title: "Ghost's Afraid of the Dark",
        author: "By Hof Nurgin, Mesho Buvahr",
        price: "£16.00",
        image: "/images/shop8.jpg",
        slug: "ghosts-afraid-of-the-dark",
        badge: "SALE",
        order: 2,
      },
      {
        id: "cmtr3nv8y000imuxzlxfnidu7",
        title: "The Summer of Impossible Things",
        author: "By CHAI IAM, HOF NURGIN",
        price: "£24.00",
        image: "/images/shop7.webp",
        slug: "the-summer-of-impossible-things",
        order: 2,
      },
      {
        id: "cmtv4vwv60000gzjjhqaot6t2",
        title: "A Poem for Every Night",
        author: "By CHAI IAM, HOF NURGIN",
        price: "£22.00",
        image: "/images/Newest2.webp",
        slug: "a-poem-for-every-night",
        order: 3,
      },
    ],
  },
  {
    id: "mta_1789019925322_uvej",
    authorName: "John Walker",
    authorImage: "/images/author-08 (1).jpg",
    quote: "My books are marked down because most of them are marked with a on the edge by publishers.",
    facebook: "#facebook",
    twitter: "#twitter",
    linkedin: "#linkedin",
    instagram: "#instagram",
    books: [
      {
        id: "cmtr3nv89000fmuxz1vjzsasf",
        title: "The Journey of Dreams",
        author: "By BHUZUN NAHLAM, JOHN WALKER",
        price: "£12.00",
        image: "/images/Newest3.webp",
        slug: "the-journey-of-dreams",
        badge: "HOT",
        order: 0,
      },
    ],
  },
  {
    id: "mta_1789019925294_i55y",
    authorName: "Mesho Buvahr",
    authorImage: "/images/author-06 (1).jpg",
    quote: "My books are marked down because most of them are marked with a on the edge by publishers.",
    facebook: "#facebook",
    twitter: "#twitter",
    linkedin: "#linkedin",
    instagram: "#instagram",
    books: [
      {
        id: "cmtr3nv7s000dmuxzjd7adv5m",
        title: "The Carrot Hunt",
        author: "By NOREEN HARRIS",
        price: "£15.00",
        image: "/images/shop5.jpg",
        slug: "the-carrot-plan",
        order: 0,
      },
      {
        id: "cmtr3nv7k000cmuxz4f9vo5mz",
        title: "The Assault",
        author: "By MARCUS HATHAWAY",
        price: "£13.00",
        image: "/images/book_section4.webp",
        slug: "the-minds-mastery",
        order: 1,
      },
      {
        id: "cmtr3nv6d0007muxzamjlu4vi",
        title: "Ghost's Afraid of the Dark",
        author: "By Hof Nurgin, Mesho Buvahr",
        price: "£16.00",
        image: "/images/shop8.jpg",
        slug: "ghosts-afraid-of-the-dark",
        badge: "SALE",
        order: 2,
      },
      {
        id: "cmtr3nv5w0005muxzgcjlhgz0",
        title: "Dear Brain",
        author: "MESHO BUVAHR",
        price: "£18.00",
        image: "/images/shop4.jpg",
        slug: "dear-brain",
        badge: "SALE",
        order: 3,
      },
    ],
  },
  {
    id: "mta_1789020346273_my00",
    authorName: "Sero Glan",
    authorImage: "/images/author-04 (1).jpg",
    quote: "My books are marked down because most of them are marked with a on the edge by publishers.",
    facebook: "#facebook",
    twitter: "#twitter",
    linkedin: "#linkedin",
    instagram: "#instagram",
    books: [
      {
        id: "cmtr3nv8q000hmuxzfrgu219g",
        title: "The Night Ocean",
        author: "By SERO GLAN, SI MODARSK",
        price: "£22.00",
        oldPrice: "£25.00",
        image: "/images/book_section3.webp",
        slug: "the-night-ocean",
        badge: "SALE",
        order: 0,
      },
      {
        id: "cmtr3nv5h0003muxzkl31b7s6",
        title: "Bulle und Pelle",
        author: "By Sero Glan, Shia Ung",
        price: "£28.00",
        image: "/images/Newest5.webp",
        slug: "bulle-und-pelle",
        badge: "SALE",
        order: 2,
      },
    ],
  },
  {
    id: "mta_1789019925370_jy1f",
    authorName: "Si Modarsk",
    authorImage: "/images/author-02.jpg",
    quote: "My books are marked down because most of them are marked with a on the edge by publishers.",
    facebook: "#facebook",
    twitter: "#twitter",
    linkedin: "#linkedin",
    instagram: "#instagram",
    books: [
      {
        id: "cmtr3nv8q000hmuxzfrgu219g",
        title: "The Night Ocean",
        author: "By SERO GLAN, SI MODARSK",
        price: "£22.00",
        oldPrice: "£25.00",
        image: "/images/book_section3.webp",
        slug: "the-night-ocean",
        badge: "SALE",
        order: 0,
      },
      {
        id: "cmtr3nv7k000cmuxz4f9vo5mz",
        title: "The Assault",
        author: "By MARCUS HATHAWAY",
        price: "£13.00",
        image: "/images/book_section4.webp",
        slug: "the-minds-mastery",
        order: 1,
      },
      {
        id: "cmtr3nv7a000bmuxzii6hi4l3",
        title: "Some Bodies is Not Broken",
        author: "By STEPHANIE FOO",
        price: "£14.00",
        image: "/images/Newest6.webp",
        slug: "some-bodies-is-not-broken",
        badge: "SALE",
        order: 2,
      },
    ],
  },
  {
    id: "mta_1789023420968_v5sf",
    authorName: "Te Sorkaz",
    authorImage: "/images/author-09 (1).jpg",
    quote: "My books are marked down because most of them are marked with a on the edge by publishers.",
    facebook: "#facebook",
    twitter: "#twitter",
    linkedin: "#linkedin",
    instagram: "#instagram",
    books: [
      {
        id: "cmtr3nv7a000bmuxzii6hi4l3",
        title: "Some Bodies is Not Broken",
        author: "By STEPHANIE FOO",
        price: "£14.00",
        image: "/images/Newest6.webp",
        slug: "some-bodies-is-not-broken",
        badge: "SALE",
        order: 0,
      },
      {
        id: "cmtr3nv5w0005muxzgcjlhgz0",
        title: "Dear Brain",
        author: "MESHO BUVAHR",
        price: "£18.00",
        image: "/images/shop4.jpg",
        slug: "dear-brain",
        badge: "SALE",
        order: 1,
      },
    ],
  },
];
